/// Flutter icons AppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData terms = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_quote = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData run = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cube = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spa = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_blank_outline = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cards_heart = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_variant = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_marked = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
